BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXX
            BBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXX
            XXXX
            BBBBB
            XXXX XXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                                
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBB  BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBBB
                                BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBB  BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                                
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                                BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBB BB BBBBBBBB  BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBBB
                                BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBB BB BBBBBBBB  BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                                
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBB BB BBBB BBBBBBBBBB  BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBBB
                                BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBB BB BBBB BBBBBBBBBB  BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBBB
                                BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
                                BBBBB
                            XXXXXX
                        XXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXX
                            XXXX
                                XXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXX
                                XXXXXXXX X XXXXXXXXX
                                XXXXXXXX XXXXXXXXXXXXXX
                                BBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                                BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                                XXXXXXXXXXXXXXX
                                BBBBB
                                BBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                                BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                                XXXXXXXXXXXXXXXX
                                BBBBB
                            XXXXX
                        XXXXXXXX
                        XXXXXXX
                            BBB BBBBB BB BBBBBBBBBBB
                            XXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXX
                                XXXXXX FFFFFFFFFFFFFXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                BBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                                BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                                XXX XXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXX
                                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXX
                                XXXXX
                                BBBBB
                                BBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                                BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                                XXX XXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXX XXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XX XXXXXXXXXX XXXXXXXXXXXX
                                    XXXX
                                XXXXX
                                BBBBB
                            XXXXX
                            BBBBBB
                        XXXXXXXX
                        XXXXXXX
                            XXXX
                                XXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXX
                                XXXXXXXX X XXXXXXXXX
                                XXXXXXXX XXXXXXXXXXXXXX
                                BBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                                BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                                XXXXXXXXXXXXXXX
                                BBBBB
                                BBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                                BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                                XXXXXXXXXXXXXXXX
                                BBBBB
                            XXXXX
                        XXXXXXXX
                    XXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXX
XXXXXX

BBBBBBBB

BBBBB BBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXX X
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
            XXXXXXXXXXX XXXX
        X XX
    X XX
XXXXXXXXX

XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXX XXXX X XXXXXXXXXXXXXXXXXXXX
        XXX XX X XXXXXXXXXXXXXXXXXX
        XXX XXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXX XXXXXXX X XXXXX XX XXXXXX XXX XXXX X XXX X X XXXX X XXXXXXX
    X
XXXXXXXXX

XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
XXXXXXXXX

BBBBBBBB