# Generated by Django 3.2.12 on 2022-02-10 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0005_colaborador_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Telefone Inválido', regex='\\([\\d]{2}\\) [\\d]{5}-[\\d]{4}')]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Telefone Inválido', regex='\\([\\d]{2}\\) [\\d]{5}-[\\d]{4}')]),
        ),
    ]
