# Generated by Django 3.2.12 on 2022-02-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0007_produto_venda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['valor'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
