# Generated by Django 3.2.12 on 2022-02-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0009_venda_data_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='venda',
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ManyToManyField(blank=True, related_name='produtos_venda', to='comercio.Produto', verbose_name='Produtos'),
        ),
    ]
