# Generated by Django 3.2.12 on 2022-02-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0011_auto_20220210_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='venda',
        ),
        migrations.AddField(
            model_name='venda',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_item', to='comercio.item'),
        ),
    ]
