BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                                
                                BB BBBBBBBBBBBBBBBB
                                BBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBBB
                                BBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBB
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                                
                                BB BBBBBBBBBBBBBBBBB
                                BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBBB
                                BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                                
                                BB BBBBBBBBBBBBBBBBBBBBBB
                                BBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBBB
                                BBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
                                BBBBB
                            XXXXXX
                        XXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXBB BBBBBBBBBXXXXXXBBBBXXXXXXXXXBBBBBXXXXXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXX XXXXXXXX XXX XXXXXXXX XXXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
